import XCTest

@testable import LocalFlow

/// T083 — `contracts/ui.md` "Copy": a plain report with title and date,
/// headings and `- ` bullets in reading order, and no internal identifiers,
/// state words, confidence values, evidence classes or schema keys.
final class AnalysisReportTests: XCTestCase {

  /// The full shape: title and date first, then Summary, topic headings with
  /// bullets, Action items, the four lists in contract order, and the single
  /// trailing line.
  func testReportOrderHeadingsBulletsAndTrailingLine() {
    let read = model(
      summary: "The team agreed the rollout moves to Friday.",
      topics: [
        topic(
          title: "Rollout plan", summary: "A short topic summary.",
          bullets: ["Beta ships first", "Docs follow the release"])
      ],
      actionItems: [
        action(
          text: "Send the agenda", owner: participant("Martin K."), due: "2026-09-21",
          status: .open),
        action(text: "Book the room", owner: participant("Peter S."), status: .completed),
        action(text: "Dropped item", owner: participant("Peter S."), status: .dismissed),
        action(text: "Chase the vendor", owner: .unresolved(label: "Speaker 3"), status: .open),
        action(
          text: "Call the lawyer", owner: .mentioned(name: "Jana", suggestion: nil),
          status: .open),
      ],
      nextSteps: [item(text: "Prepare the beta")],
      decisions: [item(text: "Ship Friday")],
      openQuestions: [item(text: "Who owns support?")],
      risks: [item(text: "Docs may slip")])

    let text = AnalysisReport.text(
      model: read, title: "Deployment sync", date: "20 Sep 2026")
    let lines = text.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)

    XCTAssertEqual(lines[0], "Deployment sync")
    XCTAssertEqual(lines[1], "20 Sep 2026")
    XCTAssertEqual(lines[3], "Summary")
    XCTAssertEqual(lines[4], "The team agreed the rollout moves to Friday.")

    // Headings appear in contract order.
    let headings = [
      "Summary", "Rollout plan", "Action items", "Next steps",
      "Decisions", "Open questions", "Risks / blockers",
    ]
    var cursor = 0
    for heading in headings {
      guard let index = lines[cursor...].firstIndex(of: heading) else {
        XCTFail("missing heading \(heading)")
        return
      }
      cursor = index
    }

    XCTAssertTrue(lines.contains("- Beta ships first"))
    XCTAssertTrue(lines.contains("- Docs follow the release"))
    XCTAssertTrue(
      lines.contains("- [ ] Send the agenda — Martin K. (due 21 Sep)"))
    XCTAssertTrue(lines.contains("- [x] Book the room — Peter S."))
    XCTAssertTrue(lines.contains("- [ ] Chase the vendor — (owner unresolved)"))
    XCTAssertTrue(
      lines.contains("- [ ] Call the lawyer — Jana"),
      "a mentioned owner is the bare name")
    XCTAssertFalse(
      lines.contains { $0.contains("Dropped item") }, "dismissed items are omitted")
    XCTAssertTrue(lines.contains("- Prepare the beta"))
    XCTAssertTrue(lines.contains("- Ship Friday"))
    XCTAssertTrue(lines.contains("- Who owns support?"))
    XCTAssertTrue(lines.contains("- Docs may slip"))
    XCTAssertEqual(lines.last, AnalysisReport.trailingLine)
    XCTAssertEqual(
      lines.last, "Generated by LocalFlow from the meeting transcript and notes.")
  }

  /// Empty sections are absent entirely — no heading, no gap of dead space.
  func testEmptySectionsAreAbsent() {
    let read = model(summary: "Short.", nextSteps: [item(text: "Follow up")])
    let text = AnalysisReport.text(model: read, title: "T", date: "D")
    XCTAssertFalse(text.contains("Action items"))
    XCTAssertFalse(text.contains("Decisions"))
    XCTAssertFalse(text.contains("Open questions"))
    XCTAssertFalse(text.contains("Risks / blockers"))
    XCTAssertTrue(text.contains("Next steps"))
  }

  /// FR-040: no UUID, no ownership/due-date state word, no evidence-class
  /// value, no `note:<n>` id and no schema key survives into the report.
  /// `(owner unresolved)` is the contract's own phrase and is excused first.
  func testReportContainsNoInternalVocabulary() {
    let read = model(
      summary: "Body.",
      actionItems: [
        action(text: "Task", owner: participant("Ana"), due: "2026-09-21", status: .open),
        action(text: "Other", owner: .unresolved(label: "Speaker 3"), status: .open),
      ],
      decisions: [item(text: "Go")])
    let text = AnalysisReport.text(model: read, title: "T", date: "D")
      .replacingOccurrences(of: "(owner unresolved)", with: "")

    let uuid = try! NSRegularExpression(
      pattern: "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")
    XCTAssertNil(uuid.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)))
    XCTAssertNil(text.range(of: #"note:\d+"#, options: .regularExpression))

    let forbidden = [
      "explicit", "supported", "unresolved", "confirmed", "recognized", "possible",
      "implied", "evidence_class", "ownership_state", "due_state", "speaker_id",
      "run_id", "meeting_id", "action_item", "next_step", "open_question",
      "timed_out", "superseded", "confidence",
    ]
    for word in forbidden {
      XCTAssertFalse(text.contains(word), "report leaks \(word)")
    }
  }

  /// `dueText` renders ISO dates as "21 Sep" and leaves anything else alone.
  func testDueTextFormats() {
    XCTAssertEqual(AnalysisReport.dueText("2026-09-21"), "21 Sep")
    XCTAssertEqual(AnalysisReport.dueText("2026-01-05"), "5 Jan")
    XCTAssertEqual(AnalysisReport.dueText("soon"), "soon")
  }

  // MARK: Helpers

  private func participant(_ name: String) -> OwnerLabel {
    .participant(name: name, colorIndex: 1, certainty: .confirmed)
  }

  private func topic(title: String, summary: String, bullets: [String]) -> TopicReadModel {
    TopicReadModel(
      id: UUID(), title: title, summary: summary, bullets: bullets, sources: [])
  }

  private func item(text: String) -> ItemReadModel {
    ItemReadModel(
      id: UUID(), kind: .decision, ordinal: 1, text: text, aiText: text, sources: [])
  }

  private func action(
    text: String, owner: OwnerLabel, due: String? = nil,
    status: AnalysisItemStatus = .open
  ) -> ActionItemReadModel {
    ActionItemReadModel(
      id: UUID(), ordinal: 1, text: text, aiText: text, owner: owner, aiOwner: owner,
      ownershipState: .supported, dueDate: due, dueOriginal: due,
      dueState: due == nil ? .absent : .explicitAbsolute, status: status, sources: [])
  }

  private func model(
    summary: String = "", topics: [TopicReadModel] = [],
    actionItems: [ActionItemReadModel] = [], nextSteps: [ItemReadModel] = [],
    decisions: [ItemReadModel] = [], openQuestions: [ItemReadModel] = [],
    risks: [ItemReadModel] = []
  ) -> MeetingAnalysisReadModel {
    MeetingAnalysisReadModel(
      summary: SummaryReadModel(text: summary, aiText: summary, edited: false, sources: []),
      topics: topics, actionItems: actionItems, nextSteps: nextSteps,
      decisions: decisions, openQuestions: openQuestions, risks: risks,
      previousEdits: [], readingMinutes: 1, evidenceVersion: "", stale: false,
      generatedAt: 0, backendModel: "")
  }
}
