import Foundation

/// `contracts/ui.md` "Copy": a plain human-readable report — title and date,
/// headings and `- ` bullets in reading order. It never contains identifiers,
/// ownership or due-date state words, confidence values, evidence classes or
/// schema keys. The only mention of the generator is the one trailing line.
enum AnalysisReport {
  static let trailingLine =
    "Generated by LocalFlow from the meeting transcript and notes."

  static func text(model: MeetingAnalysisReadModel, title: String, date: String) -> String {
    var lines: [String] = [title, date, "", "Summary", model.summary.text, ""]
    for topic in model.topics {
      lines.append(topic.title)
      if !topic.summary.isEmpty { lines.append(topic.summary) }
      for bullet in topic.bullets { lines.append("- \(bullet)") }
      lines.append("")
    }
    if !model.actionItems.isEmpty {
      lines.append("Action items")
      for item in model.actionItems where item.status != .dismissed {
        lines.append(actionLine(item))
      }
      lines.append("")
    }
    for (heading, rows) in [
      ("Next steps", model.nextSteps), ("Decisions", model.decisions),
      ("Open questions", model.openQuestions), ("Risks / blockers", model.risks),
    ] where !rows.isEmpty {
      lines.append(heading)
      for row in rows { lines.append("- \(row.text)") }
      lines.append("")
    }
    lines.append(trailingLine)
    return lines.joined(separator: "\n")
  }

  /// `- [ ] task — Owner (due 21 Sep)`; `- [x] …` when completed; `(owner
  /// unresolved)` for an unresolved owner; a bare name for mentioned owners.
  private static func actionLine(_ item: ActionItemReadModel) -> String {
    let check = item.status == .completed ? "[x]" : "[ ]"
    var line = "- \(check) \(item.text)"
    switch item.owner {
    case .participant(let name, _, _), .mentioned(let name, _):
      line += " — \(name)"
    case .unresolved:
      line += " — (owner unresolved)"
    }
    if let due = item.dueDate { line += " (due \(dueText(due)))" }
    return line
  }

  /// `YYYY-MM-DD` → "21 Sep" for the copy line's `(due 21 Sep)`.
  static func dueText(_ date: String) -> String {
    let parts = date.split(separator: "-")
    guard parts.count == 3, let month = Int(parts[1]), let day = Int(parts[2]),
      (1...12).contains(month)
    else { return date }
    let names = [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ]
    return "\(day) \(names[month - 1])"
  }
}
